import Head from "next/head"
import {useEffect, useLayoutEffect, useReducer, useState} from "react"
import styles from "../styles/Counter.module.css"

const countReducer = (state, action) => {
	switch (action.type) {
		case "INCREAMENT":
			return state + 1
		case "DECREAMENT":
			return state - 1
		default:
			return state
	}
}

export default function Home() {
	const [width, setWidth] = useState(0)
	const [leftActive, setLeftActive] = useState(false)
	const [rightActive, setRightActive] = useState(false)
	const [count, dispatch] = useReducer(countReducer, 0)

	const onWindowClick = (e) => {
		if (e.pageX <= width / 2) {
			console.log("LEFT")
			dispatch({type: "DECREAMENT"})
		} else {
			console.log("RIGHT")
			dispatch({type: "INCREAMENT"})
		}
	}

	const onChangeWindowSize = () => {
		setWidth(window.innerWidth)
	}

	useEffect(() => {
		window.addEventListener("resize", (e) => onChangeWindowSize(e))
		setWidth(window.innerWidth)

		return window.removeEventListener("resize", (e) => onChangeWindowSize(e))
	}, [width])

	return (
		<div onClick={onWindowClick} className={styles.container}>
			<Head>
				<title>A Simple Counter</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className={styles.state_container}>{count}</div>
			<div
				onClick={() => {
					setLeftActive(true)
				}}
				className={leftActive ? styles.left_active : styles.left}
				onMouseOver={() => setLeftActive(true)}
				onMouseOut={() => setLeftActive(false)}>
				{leftActive ? "DECREASE" : null}
			</div>
			<div
				onClick={() => {
					setRightActive(true)
				}}
				onMouseOver={() => setRightActive(true)}
				onMouseOut={() => setRightActive(false)}
				className={rightActive ? styles.right_active : styles.right}>
				{rightActive ? "INCREASE" : null}
			</div>
		</div>
	)
}
