import Head from "next/head"
import Link from "next/link"
import styles from "../styles/Home.module.css"

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>A Simple Counter</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className={styles.state_container}>
				<Link href="/counter">
					<a className={styles.counter_button}>Go To Counter</a>
				</Link>
				<Link href="/toggle">
					<a style={{marginLeft:"0.5rem"}} className={styles.counter_button}>Go To Toggle</a>
				</Link>
			</div>
		</div>
	)
}
