import Head from "next/head"
import Image from "next/image"
import {useEffect, useReducer, useState} from "react"
import styles from "../styles/Home.module.css"

export default function Home() {
	const [width, setWidth] = useState(0)
	const [leftActive, setLeftActive] = useState(false)
	const [rightActive, setRightActive] = useState(false)
	const [count, dispatch] = useReducer((currentCount, dispatchValue) => {
		return currentCount + dispatchValue
	}, 0)

	const onWindowClick = (e) => {
		if (e.pageX <= width / 2) {
			dispatch(-1)
		} else {
			dispatch(1)
		}
	}

	useEffect(() => {
		setWidth(window.innerWidth)
	}, [width])

	return (
		<div onClick={onWindowClick} className={styles.container}>
			<Head>
				<title>A Simple Counter</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className={styles.state_container}>{count}</div>
			<div
				onClick={() => {
					setLeftActive(true)
				}}
				className={leftActive ? styles.left_active : styles.left}
				onMouseOver={() => setLeftActive(true)}
				onMouseOut={() => setLeftActive(false)}
			>
        	{leftActive ? "DECREASE" : null}
      </div>
			<div
				onClick={() => {
					setRightActive(true)
				}}
				onMouseOver={() => setRightActive(true)}
				onMouseOut={() => setRightActive(false)}
				className={rightActive ? styles.right_active : styles.right}>
				{rightActive ? "INCREASE" : null}
			</div>
		</div>
	)
}
